### ISSUE TITLE
Dependencies...

### ISSUE THREAD

**Issue by ghost** [ffggrz/ext-respondd#1]
Could we please reduce deps as much as possible..
I'm not that familiar with Python, but why do you need python-cpuinfo? Isn't that data available in /proc?

**Comment by Sunz3r** [comment]
cpuinfo removed, thanks!

**Comment by ghost** [comment]
Can we make lsb_release optional?
What do you need ethtool for?
netifaces I kinda understand, but the data is in /proc too. 
I just think it's really annoying to guess package names for python modules and in the end install waaay too many packages (py2-versions and other versions of the module).

**Comment by anoymouserver** [comment]
- `ethtool` is used for network statistics (`ethtool -S bat0`)
- `python3-netifaces` could be replaced, but I won't do it (but you could create a PR)

Guessing of the package names is not required since they are listed in the README.

**Comment by ghost** [comment]
Thanks! 
:)
