### ISSUE TITLE
Multirequest answer with one respond

### ISSUE THREAD

**Issue by genofire** [ffggrz/ext-respondd#2]
And compressed

**Comment by Sunz3r** [comment]
it should working

https://github.com/ffggrz/ext-respondd/blob/master/ext-respondd.py#L521


pls try also the dev-branch https://github.com/ffggrz/ext-respondd/tree/dev-oo-code-rework

**Comment by genofire** [comment]
okay, looks like compressen works:
but it still sends multiple response:
https://github.com/ffggrz/ext-respondd/blob/dev-oo-code-rework/lib/respondd_client.py#L57

**Comment by Sunz3r** [comment]
thx for advice ... it should now work with yanic
